#!/bin/bash
# Read the /etc/passwd file, extract username and home directory,and sort by username
while IFS=: read -r username _ _ _ _ home_directory _
do
    echo "User: $username, Home Directory: $home_directory"
done < /etc/passwd | sort -t : -k 1